### ISSUE TITLE
site-context.xml is for tomcat 8

### ISSUE THREAD

**Issue by clouddistortion** [jreijn/hippocms-spring-loaded#1]
Hi,
I am having problems getting it to run with cargo using tomcat 8. org.apache.catalina.loader.VirtualWebappLoader isn't available anymore in tomcat 8. I guess the site-context.xml needs to be migrated with https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/WebResourceRoot.html 

just an idea, didn't spent so much time on it

**Comment by jreijn** [comment]
Fixed in the Hippo 10 branch. See https://github.com/jreijn/hippocms-spring-loaded/blob/19946040890745a3b6d76955cea20dca0ad0386a/conf/site-context.xml

**Comment by clouddistortion** [comment]
great thanks a lot. Works now, although Spring is complaining with the following error:
SEVERE [FileSystemWatcher: files=#34 cl=WebappClassLoader
[INFO] [talledLocalContainer]   context: ROOT
[INFO] [talledLocalContainer]   delegate: false
[INFO] [talledLocalContainer] ----------> Parent Classloader:
[INFO] [talledLocalContainer] java.net.URLClassLoader@1d3bb75d
[INFO] [talledLocalContainer] ] org.springsource.loaded.agent.Watcher.determineChangesSince FileWatcher caught serious error, see cause
[INFO] [talledLocalContainer]  java.lang.IllegalArgumentException: Can not set final java.util.Map field org.springframework.core.LocalVariableTableParameterNameDiscoverer.parameterNamesCache to org.springframework.core.LocalVariableTableParameterNameDiscoverer
